Traceback (most recent call last):
  File "main.py", line 74, in <module>
    main()
  File "main.py", line 57, in main
    plt.plot(list_of_dims, list_of_numpy_times, 'b', label='Numpy')
  File "/home/bbc33/anaconda3/envs/pycuda/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2795, in plot
    is not None else {}), **kwargs)
  File "/home/bbc33/anaconda3/envs/pycuda/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 1666, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/home/bbc33/anaconda3/envs/pycuda/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 225, in __call__
    yield from self._plot_args(this, kwargs)
  File "/home/bbc33/anaconda3/envs/pycuda/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 391, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/home/bbc33/anaconda3/envs/pycuda/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 270, in _xy_from_xy
    "have shapes {} and {}".format(x.shape, y.shape))
ValueError: x and y must have same first dimension, but have shapes (32, 3) and (16,)
