/home/bbc33/anaconda3/envs/cupy/lib/python3.12/site-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
Traceback (most recent call last):
  File "/home/bbc33/anaconda3/envs/cupy/lib/python3.12/site-packages/numba/cuda/cudadrv/driver.py", line 2830, in add_ptx
    driver.cuLinkAddData(self.handle, enums.CU_JIT_INPUT_PTX,
  File "/home/bbc33/anaconda3/envs/cupy/lib/python3.12/site-packages/numba/cuda/cudadrv/driver.py", line 327, in safe_cuda_api_call
    self._check_ctypes_error(fname, retcode)
  File "/home/bbc33/anaconda3/envs/cupy/lib/python3.12/site-packages/numba/cuda/cudadrv/driver.py", line 395, in _check_ctypes_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [222] Call to cuLinkAddData results in CUDA_ERROR_UNSUPPORTED_PTX_VERSION

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/bbc33/pycuda/cupy/ex1/main.py", line 63, in <module>
    main()
  File "/scratch/bbc33/pycuda/cupy/ex1/main.py", line 44, in main
    test_kernel(dims, methods, validation_method)
  File "/scratch/bbc33/pycuda/cupy/ex1/main.py", line 8, in test_kernel
    test.test_all()
  File "/scratch/bbc33/pycuda/cupy/ex1/testbench.py", line 39, in test_all
    instance.run()
  File "/scratch/bbc33/pycuda/cupy/ex1/matmul.py", line 78, in run
    self._dot[self.BPG, self.TPB](dA, dB, dC)
  File "/home/bbc33/anaconda3/envs/cupy/lib/python3.12/site-packages/numba/cuda/dispatcher.py", line 539, in __call__
    return self.dispatcher.call(args, self.griddim, self.blockdim,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bbc33/anaconda3/envs/cupy/lib/python3.12/site-packages/numba/cuda/dispatcher.py", line 681, in call
    kernel = _dispatcher.Dispatcher._cuda_call(self, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bbc33/anaconda3/envs/cupy/lib/python3.12/site-packages/numba/cuda/dispatcher.py", line 689, in _compile_for_args
    return self.compile(tuple(argtypes))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bbc33/anaconda3/envs/cupy/lib/python3.12/site-packages/numba/cuda/dispatcher.py", line 934, in compile
    kernel.bind()
  File "/home/bbc33/anaconda3/envs/cupy/lib/python3.12/site-packages/numba/cuda/dispatcher.py", line 197, in bind
    self._codelibrary.get_cufunc()
  File "/home/bbc33/anaconda3/envs/cupy/lib/python3.12/site-packages/numba/cuda/codegen.py", line 214, in get_cufunc
    cubin = self.get_cubin(cc=device.compute_capability)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bbc33/anaconda3/envs/cupy/lib/python3.12/site-packages/numba/cuda/codegen.py", line 188, in get_cubin
    linker.add_ptx(ptx.encode())
  File "/home/bbc33/anaconda3/envs/cupy/lib/python3.12/site-packages/numba/cuda/cudadrv/driver.py", line 2833, in add_ptx
    raise LinkerError("%s\n%s" % (e, self.error_log))
numba.cuda.cudadrv.driver.LinkerError: [222] Call to cuLinkAddData results in CUDA_ERROR_UNSUPPORTED_PTX_VERSION
ptxas application ptx input, line 9; fatal   : Unsupported .version 7.8; current version is '7.4'
